### ISSUE TITLE
log4js-0.7.0

### ISSUE THREAD

**Issue by madhandennis** [nomiddlename/log4js-gelf#1]
Hi,

Looks like log4js-gelf requires log4js 0.7.0. However the latest version I am able to find for log4js is 0.6.9. Hence log4js-gelf does not install due to unmet dependencies. Any suggestions?

Thanks

Best Regards,
Madhan

**Comment by nomiddlename** [comment]
log4js 0.7 hasn't been released yet, sorry for the confusion. The GELF appender is included in the core log4js in version 0.6.9 though, you don't need this module if you're using 0.6.9.

**Comment by madhandennis** [comment]
Awesome. Thanks for the clarification :D
